name: Cancel
on: [push]
jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          workflow_id: 7468189
          access_token: ${{ github.token }}

      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          workflow_id: 7443883
          access_token: ${{ github.token }}

      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          workflow_id: 7443884
          access_token: ${{ github.token }}
